apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "rate-observer.fullname" . }}
  labels:
    app: {{ template "rate-observer.name" . }}
    chart: {{ template "rate-observer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rate-observer.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "rate-observer.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.service.internalPort}}
              externalPort: {{.Values.service.externalPort}}
              protocol: TCP
